version: "3.9"
services:
  emission-backend:
    build: ./emission-backend
    ports:
      - "8080:8080"
    container_name: emission-backend
    expose:
      - 8080
    extra_hosts:
      - "localhost:127.0.0.1"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
      SPRING_DATASOURCE_USERNAME: postgres.lkrpcyqhmzrhrqzbolsb
      SPRING_DATASOURCE_PASSWORD: x2c3v4b5n6m7
