
spring:
  application:
    name: emission-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/emission_db
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: hackathon

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true




