
spring:
  application:
    name: emission-backend
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
    username: postgres.lkrpcyqhmzrhrqzbolsb
    password: x2c3v4b5n6m7
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true




